name: seemur_v1
description: A new Flutter project.


version: 1.1.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  loading: ^1.0.2
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.4
  firebase_analytics: ^5.0.11
  flutter_auth_buttons: ^0.6.0
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.13.3
  flutter_svg: ^0.17.1
  cupertino_icons: ^0.1.3
  rect_getter: ^0.0.1
  shared_preferences: ^0.5.6+1
  path_provider: ^1.6.0
  intro_slider: ^2.2.9
  modal_progress_hud: ^0.1.3
  intl: ^0.16.0
  datetime_picker_formfield: ^1.0.0-pre.5
  firebase_storage_image: ^0.4.0
  date_format: ^1.0.8
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_web_view: ^0.0.6
  url_launcher: ^5.4.1
  font_awesome_flutter: ^8.7.0
  flutter_webview_plugin: ^0.3.10+1
  flutter_responsive_screen: ^1.0.0
  flutter_launcher_icons: ^0.7.4
  flutter_range_slider: ^1.4.0
  smooth_star_rating: ^1.0.4+2
  provider: ^4.0.4
  cached_network_image: ^2.0.0-rc.1
  flutter_image_compress: ^0.6.5+1
  uuid: ^2.0.4
  flutter_swiper: ^1.1.6
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.24
  geolocator: ^5.2.1
  share: ^0.6.3+5
  auto_size_text: ^2.1.0







dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"





flutter:
  fonts:
     - family: HankenGrotesk
       fonts:
         - asset: fonts/HankenGrotesk-Regular.ttf
         - asset: fonts/HankenGrotesk-Bold.ttf
           #weight: 700
         - asset: fonts/HankenGrotesk-Light.ttf
           #weight: 300
           #style: italic
         - asset: fonts/HankenGrotesk-Black.ttf
         - asset: fonts/HankenGrotesk-ExtraLight.ttf
         - asset: fonts/HankenGrotesk-Medium.ttf
         - asset: fonts/HankenGrotesk-SemiBold.ttf
     - family: OpenSans
       fonts:
         - asset: fonts/OpenSans-Bold.ttf
         - asset: fonts/OpenSans-BoldItalic.ttf
         - asset: fonts/OpenSans-ExtraBold.ttf
         - asset: fonts/OpenSans-ExtraBoldItalic.ttf
         - asset: fonts/OpenSans-Italic.ttf
         - asset: fonts/OpenSans-Light.ttf
         - asset: fonts/OpenSans-LightItalic.ttf
         - asset: fonts/OpenSans-Regular.ttf
         - asset: fonts/OpenSans-SemiBold.ttf
         - asset: fonts/OpenSans-SemiBoldItalic.ttf
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  assets:
    - assets/
    - assets/images/
    - assets/seemurIsotipo.png
    - assets/logoSombrero.png
    - assets/logoblanco.png
    - assets/icon/icon.png
    - assets/images/seemurapp.gif
    - assets/images/seemurapp2.gif
    - assets/images/seemurapp3.gif
        

      